### ISSUE TITLE
PDOException after php artisan migrate command

### ISSUE THREAD

**Issue by chris-exu** [bigappleinsider/browserstackapi#1]
Hi, 
after the php artisan migrate command follows this error:

![image](https://user-images.githubusercontent.com/39409076/40236648-8e667e80-5aae-11e8-9179-33781c4f1719.png)

Any idea whats wrong?
Thx for your help

**Comment by bigappleinsider** [comment]
This could be configuration issue with MySQL 
https://www.google.com/search?q=php+artisan+migrate+no+such+file+or+directory&oq=php+artisan+migrate
